
POST http://localhost:3001/sessions  HTTP/1.1
Content-Type: application/json
    
    {
      "username": "john.doe@polito.it",
      "password": "password"
    }

###
GET http://localhost:3001/sessions/current  HTTP/1.1