POST http://localhost:3001/tasks
Content-Type: application/json



    {"description":"uu",
    "priv":1,
    "important":0, 
    "deadline": "",
    "completed":0, 
    "user":1
    
    }
###
DELETE  http://localhost:3001/tasks/11
####

PUT  http://localhost:3001/tasks/28  HTTP/1.1
Content-Type: application/json
    
    
    {"description":"test",
    "priv":1,
    "important":0, 
    "deadline": "2021-05-11",
    "completed":1
    }

###

GET http://localhost:3001/tasks/18 HTTP/1.1